### ISSUE TITLE
bemserver_test.ttl not bemserver_tdb.ttl

### ISSUE THREAD

**Issue by arunkollan** [HIT2GAP-EU-PROJECT/bemserver#1]
Hi There ,

I am trying to install the server and there is a section "Create a new dataset called "bemserver"" using the file 

https://github.com/HIT2GAP-EU-PROJECT/bemserver/blob/master/docs/deployment/data_model/bemserver_tdb.ttl

the file does not exists 

Instead i have used this
./tests/database/ontology/bemserver_test.ttl

Time to update the documentation.

**Comment by pbourreau** [comment]
Hi sorry about that, the .ttl files had wrong names. I just updated it.
The file to use is
https://github.com/HIT2GAP-EU-PROJECT/bemserver/blob/master/docs/deployment/data_model/bemserver_tdb.ttl
Regards
